const cuponBanner = [
  {
    img: "./base/202306-cupom-adega_topo.jpg",
    descricao: "Abasteça sua adega",
    cupom: "20% de desconto nos melhores rótulos!",
    valorCupom: "vinho20",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: " 20vinho",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: " https://www.gimba.com.br/",
  },
];

const cupons = [
  {
    img: "./base/202306-cupom-organizadores.jpg",
    descricao: "Organização e praticidade no dia-a-dia",
    cupom: "10% de desconto em organizadores!",
    valorCupom: "Organize",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: "Organize10",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: " https://www.gimba.com.br/",
  },
  {
    img: "./base/202306-cupom-impressora.jpg",
    descricao: "Imprimir ficou mais fácil",
    cupom: "10% de desconto em impressoras e multifuncionais!",
    valorCupom: "Impressao",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: "Impressao10",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: " https://www.gimba.com.br/",
  },
  {
    img: "./base/202306-cupom-fita3m.jpg",
    descricao: "Cole tudo com 3M",
    cupom: "10% de desconto em fitas 3M!",
    valorCupom: "Fitas3m",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: "fitas10",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: " https://www.gimba.com.br/",
  },
  {
    img: "./base/202306-cupom-mop.jpg",
    descricao: "Mop para todo tipo de limpeza",
    cupom: "15% de desconto na compra de qualquer mop!",
    valorCupom: "15mop",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: "mop15",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: " https://www.gimba.com.br/",
  },
  {
    img: "./base/202306-cupom-johnson.jpg",
    descricao: "Facilite sua limpeza com SC Johnson",
    cupom: "10% de desconto em qualquer produto SC Johnson!",
    valorCupom: "sclimpeza",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: "johnson",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: " https://www.gimba.com.br/",
  },
  {
    img: "./base/202306-cupom-headphone.jpg",
    descricao: "Sua música com você",
    cupom: "10% de desconto em headphones!",
    valorCupom: "headphone",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: "headphone10",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: "https://www.gimba.com.br/",
  },
];

const footer = [
  {
    img: "./base/202306-cupom-destilado_topo.jpg",
    descricao: "Prepare bons drinks",
    cupom: "20% de desconto em destilados!",
    valorCupom: "Destilados",
    botao: "copiar cupom",
    cupomApp: "no app utilize o cupom",
    appCupom: "destilados20",
    zap: "https://api.whatsapp.com/send?text=Aqui%20no%20Gimba%20tem%20CUPONS%20com%20desconto%20exclusivos!%20https%3A%2F%2Fwww.gimba.com.br%2Fcupons",
    acessar: " https://www.gimba.com.br/",
  },
];
